apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{WORKSPACE_ID}}
  namespace: cloud-ide
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{HOST}}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-{{WORKSPACE_ID}}
            port:
              number: 80