apiVersion: v1
kind: Service
metadata:
  name: shell-{{WORKSPACE_ID}}
  namespace: cloud-ide
spec:
  selector:
    workspace: {{WORKSPACE_ID}}
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: vite
    protocol: TCP
    port: 5173
    targetPort: 5173